name: ci

on: pull request
jobs:
	test:
		runs-on: ubuntu-latest
		
		steps:
      - name: primeira CI
        run: echo "Hello World"

      - name: o que tem aqui?
        run: echo $(ls)
      
      - name: qual o diretório atual?
        run: echo $(pwd)

      